export default {
  products: [
    {
      id: "1",
      name: "Mobile",
      category: "mobile",
      image: "/Images/a1.jfif",
      price: 600,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: "2",
      name: "Mobile",
      category: "mobile",
      image: "/Images/a1.jfif",
      price: 600,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: "3",
      name: "Mobile",
      category: "mobile",
      image: "/Images/a1.jfif",
      price: 600,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: "4",
      name: "Mobile",
      category: "mobile",
      image: "/Images/a1.jfif",
      price: 600,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: "5",
      name: "Mobile",
      category: "mobile",
      image: "/Images/a1.jfif",
      price: 600,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: "6",
      name: "Mobile",
      category: "mobile",
      image: "/Images/a1.jfif",
      price: 600,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: "7",
      name: "Mobile",
      category: "mobile",
      image: "/Images/a1.jfif",
      price: 600,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
    },
  ],
};
